-- ============================================================================
-- Migração 020 — ESTE ARQUIVO FOI DIVIDIDO EM DOIS. Não rode este arquivo.
-- ============================================================================
--
-- A versão original deste script combinava o ALTER TYPE (vocabulário novo
-- do enum de Status) com as views que já usam os valores novos, na mesma
-- execução — e isso deu erro no SQL Editor do Supabase:
--   ERROR: 55P04: unsafe use of new value "Concluída com atraso" of enum
--   type status_atividade_enum
--   HINT: New enum values must be committed before they can be used.
-- Reproduzi a causa isoladamente (o Supabase roda o script colado inteiro
-- como uma única transação, e o Postgres recusa usar um valor de enum ainda
-- não commitado numa comparação de coluna) e a correção é rodar em duas
-- execuções separadas. Use os dois arquivos abaixo, NESTA ORDEM, cada um
-- numa execução própria no SQL Editor (rode o primeiro, confirme que
-- terminou sem erro, só depois abra e rode o segundo):
--
--   1) migration_020a_enum_status_conclusao.sql
--   2) migration_020b_views_status_conclusao.sql
--
-- Este arquivo (migration_020_classificacao_conclusao.sql) fica só como
-- registro histórico do que já pode ter sido parcialmente aplicado — se você
-- já rodou este arquivo em produção e ele falhou no meio (erro 55P04 na
-- CREATE VIEW), o ALTER TYPE de cima provavelmente já foi aplicado com
-- sucesso antes do erro (os ADD VALUE ... IF NOT EXISTS são idempotentes),
-- então rodar migration_020a de novo não faz mal (os `IF NOT EXISTS`
-- simplesmente não fazem nada se o valor já existir) — e migration_020b
-- resolve o resto.
